package com.ads.pojo;
// Generated 2018-5-10 21:48:33 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPicture generated by hbm2java
 */
@Entity
@Table(name = "t_picture", catalog = "episode")
public class TPicture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pictureId;
	private Date addDate;
	private String pictureDesc;
	private String pictureImg;
	private Integer pictureGood;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TPicComment> TPicComments = new HashSet<TPicComment>(0);
	private Set<TUser> TUsers_1 = new HashSet<TUser>(0);

	public TPicture() {
	}

	public TPicture(int pictureId, Date addDate, String pictureImg) {
		this.pictureId = pictureId;
		this.addDate = addDate;
		this.pictureImg = pictureImg;
	}

	public TPicture(int pictureId, Date addDate, String pictureDesc, String pictureImg, Integer pictureGood,
			Set<TUser> TUsers, Set<TPicComment> TPicComments, Set<TUser> TUsers_1) {
		this.pictureId = pictureId;
		this.addDate = addDate;
		this.pictureDesc = pictureDesc;
		this.pictureImg = pictureImg;
		this.pictureGood = pictureGood;
		this.TUsers = TUsers;
		this.TPicComments = TPicComments;
		this.TUsers_1 = TUsers_1;
	}

	@Id

	@Column(name = "picture_id", unique = true, nullable = false)
	public int getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(int pictureId) {
		this.pictureId = pictureId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "picture_desc", length = 150)
	public String getPictureDesc() {
		return this.pictureDesc;
	}

	public void setPictureDesc(String pictureDesc) {
		this.pictureDesc = pictureDesc;
	}

	@Column(name = "picture_img", nullable = false, length = 100)
	public String getPictureImg() {
		return this.pictureImg;
	}

	public void setPictureImg(String pictureImg) {
		this.pictureImg = pictureImg;
	}

	@Column(name = "picture_good")
	public Integer getPictureGood() {
		return this.pictureGood;
	}

	public void setPictureGood(Integer pictureGood) {
		this.pictureGood = pictureGood;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TPictures")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPicture")
	public Set<TPicComment> getTPicComments() {
		return this.TPicComments;
	}

	public void setTPicComments(Set<TPicComment> TPicComments) {
		this.TPicComments = TPicComments;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TPictures")
	public Set<TUser> getTUsers_1() {
		return this.TUsers_1;
	}

	public void setTUsers_1(Set<TUser> TUsers_1) {
		this.TUsers_1 = TUsers_1;
	}

}
